language: php

sudo: enabled

services:
  - docker

before_script:
  - docker-compose up -d
  - docker-compose exec php cp .env.travis .env
  - docker-compose exec php composer install

script:
  - docker-compose exec php vendor/bin/phpunit
