language: php

sudo: enabled

services:
  - docker

before_script:
  - docker-compose up -d
  - docker-compose exec php cp .env.travis .env
script:
  - docker-compose exec php php artisan key:generate
  - docker-compose exec php vendor/bin/phpunit
