language: php

sudo: enabled

services:
  - docker

before_script:
  - docker-compose up -d
  - docker-compose exec -T app cp .env.travis .env
  - docker-compose exec -T app php artisan key:generate
script:
  - docker-compose exec -T app vendor/bin/phpunit
