language: php

sudo: enabled

services:
  - docker

before_script:
  - docker-compose up -d
  - docker-compose exec app ls
  - docker-compose exec app cp .env.travis .env
  - docker-compose exec app php artisan key:generate
script:
  - docker-compose exec app vendor/bin/phpunit
