version: '2'
services:
  web:
    image: nginx:1.15.0
    volumes:
      - ./code:/code
    ports:
      - "8080:80"
    links:
      - php

  php:
    image: php:7.2-fpm
    volumes:
        - ./code:/code

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8889:8889